postgre:
  datasource:
    url: ${MAIN_DATASOURCE_URL}
    username: ${MAIN_DATASOURCE_USERNAME}
    password: ${MAIN_DATASOURCE_PASSWORD}
# env :
# POSTGRE_DATASOURCE_URL
# POSTGRE_DATASOURCE_USERNAME
# POSTGRE_DATASOURCE_PASSWORD